# Generated by Django 5.1.7 on 2025-03-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='price_change_24h',
            field=models.FloatField(default=0),
        ),
    ]
